apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: html-openshift-app
  namespace: 254500-fluman
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/flurin1234/modul-210
    contextDir: app            
    sourceSecret:
      name: html-openshift-app-github
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nginx:1.20-ubi7
        namespace: openshift  
  output:
    to:
      kind: ImageStreamTag
      name: html-openshift-app:latest
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: html-openshift-app-generic-webhook-secret
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
