kind: Deployment 
apiVersion: apps/v1 
metadata:
  name: html-openshift-app 
  labels:
    app: html-openshift-app 
    app.kubernetes.io/part-of: html-openshift-app 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: html-openshift-app 
  template:
    metadata:
      labels:
        app: html-openshift-app
    spec:
      volumes:
        - name: html-openshift-app-pvc 
          persistentVolumeClaim:
            claimName: html-openshift-app-pvc 
      containers: 
        - name: html-openshift-app 
          resources: {} 
          ports:
            - containerPort: 8080 
              protocol: TCP 
          volumeMounts:
            - name: html-openshift-app-pvc 
              mountPath: /opt/app-root/src/data 
          image: image-registry.openshift-image-registry.svc:5000/254500-fluman/html-openshift-app:latest 
          imagePullPolicy: Always 